### ISSUE TITLE
New Name for the Fastq To Bam Worklow:

### ISSUE THREAD

**Issue by rhshah** [msk-access/nucleo#127]
Please add the names that you feel we should call this workflow
I will add it to the poll based on your suggestion.

/polls "Ruina (collapsing in latin)" "BinaryCipher" "statCell"

**Comment by ionox0** [comment]
I would go for something like "fgbio_fastq_to_bam" or "fulcrum_collapsing_workflow"

**Comment by rhshah** [comment]
nucleo it is
