### ISSUE TITLE
ERROR I'm sorry, I couldn't load this CWL file

### ISSUE THREAD

**Issue by AdilyAid** [msk-access/nucleo#169]
* fastq_to_bam version: 3.0.4
* Python version: 3.9
* Operating System: linux

### Description

Hello, 
I try to install Nucleo in order to create MSK-ACCESS bams. 
It is recommended at the installation instructions to use python3.6, but when I install the requirements I got this:
```
Collecting toil[cwl] (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/80/02/e44397b00870b59b381b86f593fa31b57242dd12884c7831c1f725731a6b/toil-5.6.0-py3-none-any.whl (592kB)
    100% |████████████████████████████████| 593kB 1.3MB/s 
toil requires Python '>=3.7' but the running Python is 3.6.9

```
So I move to python 3.9 and the requirements installed properly. 

But when I try to generate an input file by the next command:

`$ cwltool --debug --make-template nucleo.cwl

I got the next error:
```
...
nucleo.cwl:342:5: Source 'picard_addRG_sort_order' of type ["null", "string"] may be incompatible
nucleo.cwl:825:9:   with sink 'picard_addRG_sort_order' of type "string"
nucleo.cwl:40:5:  Source 'sequencing-center' of type ["null", "string"] may be incompatible
nucleo.cwl:520:9:   with sink 'sequencing-center' of type "string"
nucleo.cwl:64:5:  Source 'platform-model' of type ["null", "string"] may be incompatible
nucleo.cwl:537:9:   with sink 'platform-model' of type "string"
nucleo.cwl:68:5:  Source 'platform' of type ["null", "string"] may be incompatible
nucleo.cwl:540:9:   with sink 'platform' of type "string"
nucleo.cwl:76:5:  Source 'validation_stringency' of type ["null", "string"] may be incompatible
nucleo.cwl:545:9:   with sink 'validation_stringency' of type "string"
nucleo.cwl:116:5: Source 'sort_order' of type ["null", "string"] may be incompatible
nucleo.cwl:576:9:   with sink 'sort_order' of type "string"
nucleo.cwl:132:5: Source 'create_bam_index' of type ["null", "boolean"] may be incompatible
nucleo.cwl:585:9:   with sink 'create_bam_index' of type "boolean"
nucleo.cwl:223:5: Source 'merge_sam_files_sort_order' of type ["null", "string"] may be incompatible
nucleo.cwl:637:9:   with sink 'merge_sam_files_sort_order' of type "string"
nucleo.cwl:342:5: Source 'picard_addRG_sort_order' of type ["null", "string"] may be incompatible
nucleo.cwl:645:9:   with sink 'picard_addRG_sort_order' of type "string"
ERROR I'm sorry, I couldn't load this CWL file.
The error was: 
Traceback (most recent call last):
  File "/home/user/soft/nucleo_venv/lib/python3.9/site-packages/cwltool/main.py", line 1168, in main
    make_template(tool)
  File "/home/user/soft/nucleo_venv/lib/python3.9/site-packages/cwltool/main.py", line 777, in make_template
    generate_input_template(tool),
  File "/home/user/soft/nucleo_venv/lib/python3.9/site-packages/cwltool/main.py", line 336, in generate_input_template
    template.insert(0, name, value, comment)
  File "/home/user/soft/nucleo_venv/lib/python3.9/site-packages/ruamel/yaml/comments.py", line 896, in insert
    self.yaml_add_eol_comment(comment, key=key)
  File "/home/user/soft/nucleo_venv/lib/python3.9/site-packages/ruamel/yaml/comments.py", line 434, in yaml_add_eol_comment
    if comment[0] != '#':
IndexError: string index out of range

```
What can be the problem?

Thank you for your help,
Adily

**Comment by rhshah** [comment]
Hi Adily, thank you for the detailed explanation! We were able to reproduce the error! But we dont have any solution currently to generate the template using cwltool. We have provided template input file here https://cmo-ci.gitbook.io/nucleo/inputs-description#template-inputs-file  you can use that as the input. Let us know if you have additional issuess

**Comment by AdilyAid** [comment]
Thank you! I used the provided template input.
Now I try to run the workflow by the command:

`cwltool nucleo.cwl inputs_test.yaml`

But I got the two next error:
ERROR Workflow error, try again with --debug for more information:
```
Invalid job input record:
inputs_test.yaml:22:1: * the `fgbio_fastq_to_bam_input` field is not valid because
                         the value
                         ('/home/user/test/test_data/test_patient_1_R1_001.fastq.g[...]
                         is not a list, expected list of array of <File>
inputs_test.yaml:27:1: * the `fgbio_group_reads_by_umi_family_size_histogram` field is not valid
                       because
                         the value is not string
```

part of the inputs_test.yaml:
```
fgbio_fastq_to_bam_input: /home/user/test/test_data/test_patient_1_R1_001.fastq.gz, /home/user/test/test_data/test_patient_R2_001.fastq.gz
fgbio_group_reads_by_umi_family_size_histogram: True
```
1. How the list of **fgbio_fastq_to_bam_input** should look like? 
2. What should I give to **fgbio_group_reads_by_umi_family_size_histogram**, if it is null - I get error this field is required, so I give the default value that mentioned on your input description - True, but is not valid.

Thank you for your help,
Adily

**Comment by AdilyAid** [comment]
And another question, where the UMIs should appear in the fastqs file?
After bcl2fastq we got separate file contain the UMIs.

**Comment by rhshah** [comment]
> Thank you! I used the provided template input. Now I try to run the workflow by the command:
> 
> `cwltool nucleo.cwl inputs_test.yaml`
> 
> But I got the two next error: ERROR Workflow error, try again with --debug for more information:
> 
> ```
> Invalid job input record:
> inputs_test.yaml:22:1: * the `fgbio_fastq_to_bam_input` field is not valid because
>                          the value
>                          ('/home/user/test/test_data/test_patient_1_R1_001.fastq.g[...]
>                          is not a list, expected list of array of <File>
> inputs_test.yaml:27:1: * the `fgbio_group_reads_by_umi_family_size_histogram` field is not valid
>                        because
>                          the value is not string
> ```
> 
> part of the inputs_test.yaml:
> 
> ```
> fgbio_fastq_to_bam_input: /home/user/test/test_data/test_patient_1_R1_001.fastq.gz, /home/user/test/test_data/test_patient_R2_001.fastq.gz
> fgbio_group_reads_by_umi_family_size_histogram: True
> ```
> 
> 1. How the list of **fgbio_fastq_to_bam_input** should look like?

Each pair of FASTQ go in as a list
```json
"fgbio_fastq_to_bam_input": [
[
        {
            "class": "File",
            "path": "/home/shahr2/bergerlab/test/nucleo_test/fastq/seracare_0-5_R1_001ad.fastq.gz"
        },
        {
            "class": "File",
            "path": "/home/shahr2/bergerlab/test/nucleo_test/fastq/seracare_0-5_R2_001ad.fastq.gz"
        }
],
[
        {
           "class": "File",
           "path": "/home/shahr2/bergerlab/test/nucleo_test/fastq/seracare_0-5_R1_001ae.fastq.gz"
        },
        {
           "class": "File",
           "path": "/home/shahr2/bergerlab/test/nucleo_test/fastq/seracare_0-5_R2_001ae.fastq.gz"
        }
]
    ],
```
> 2. What should I give to **fgbio_group_reads_by_umi_family_size_histogram**, if it is null - I get error this field is required, so I give the default value that mentioned on your input description - True, but is not valid.

This needs to be name of the histogram file, something like "samplename.hist"

> 
> Thank you for your help, Adily

**Comment by rhshah** [comment]
> And another question, where the UMIs should appear in the fastqs file? After bcl2fastq we got separate file contain the UMIs.

How you have your UMIs should be listed as required by Fgbio FastqToBam option called `read structure` check here what we have as default: https://github.com/msk-access/nucleo/blob/8e982962891d07bc7290aa8afdf5bbb4db80cfc8/nucleo.cwl#L527 you can use https://github.com/fulcrumgenomics/fgbio/wiki/Read-Structures to generate yours
