### ISSUE TITLE
What varaiant caller is recommended by msk-access?

### ISSUE THREAD

**Issue by AdilyAid** [msk-access/nucleo#171]
Hello,

On your article https://www.biorxiv.org/content/10.1101/2020.06.27.175471v1 you present the tools you used for variant calling:

```
Analysis pipeline
...
Variant calling was performed in a matched tumor-informed manner (“genotyping”) using
GetBaseCountsMultiSample (GBCM v.1.2.2, https://github.com/mskcc/GetBaseCountsMultiSample) 
when prior molecular profiling results were available for an individual.
...
De novo mutation calling by VarDict (v1.5.1) or MuTect (v1.1.5) 
...
```
I'm wondering if these are still the recommended tools for variant calling after collapsed bam creation by nucleo of msk-access, because some of these tools seems to be old (GetBaseCountsMultiSample - was updated 5 years ago)

I would appreciate your insights regarding that issue.

Thank you in advance,
Adily

**Comment by rhshah** [comment]
This deals only with BAM generation!
